DEBUG 2025-04-13 09:16:10.506 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-13 09:16:10.506 UTC: 	 Running on: Linux lxplus975.cern.ch 5.14.0-503.26.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb 10 05:23:56 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-13 09:16:10.506 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-04-13 09:16:10.506 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-13 09:16:10.506 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-13 09:16:10.510 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sarteaga/.crab3
DEBUG 2025-04-13 09:16:10.512 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
DEBUG 2025-04-14 17:59:09.367 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-14 17:59:09.368 UTC: 	 Running on: Linux lxplus987.cern.ch 5.14.0-503.26.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb 10 05:23:56 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-14 17:59:09.368 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-04-14 17:59:09.368 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-14 17:59:09.368 UTC: 	 Executing command: 'status'
DEBUG 2025-04-14 17:59:09.368 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sarteaga/.crab3
ERROR 2025-04-14 17:59:09.388 UTC: 	 Error: HeavyIon_Forest_ZB5/crab_HeavyIon_Forest_pPb_8p16TeV_pgoing_ZB_PD05/ is not a valid CRAB project directory.
ERROR 2025-04-14 17:59:09.388 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: HeavyIon_Forest_ZB5/crab_HeavyIon_Forest_pPb_8p16TeV_pgoing_ZB_PD05/ is not a valid CRAB project directory.
INFO 2025-04-14 17:59:09.471 UTC: 	 Log file is /afs/cern.ch/user/s/sarteaga/HiForest_pPb_dnr/CMSSW_8_0_28/src/HeavyIonsAnalysis/JetAnalysis/test/workstation/ZB_data/pPb_ZB/crab.log
DEBUG 2025-04-14 19:05:12.300 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-14 19:05:12.300 UTC: 	 Running on: Linux lxplus987.cern.ch 5.14.0-503.26.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb 10 05:23:56 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-14 19:05:12.300 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-04-14 19:05:12.300 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-14 19:05:12.300 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-14 19:05:12.301 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sarteaga/.crab3
DEBUG 2025-04-14 19:05:12.329 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
